[package]
name = "Ridi"
version = "0.1.0"
authors = ["Ben"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
midir = "0.5.0"
sysinputs = "0.0.5"
